name: Desktop Jvm Benchmarks

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
  

permissions:
  contents: read

jobs:
  benchmark:
    name: Desktop Jvm Benchmarks
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Ensure Gradle wrapper is executable
        run: chmod +x ./gradlew

      - name: Run benchmarks
        run: ./gradlew :collectionsBenchmarks:jvmBenchmark --no-daemon --stacktrace


